name: Benchmark PR

on: pull_request

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run benchmark on PR branch
        id: pr_benchmark
        run: |
          PR_START_TIME=$(date +%s)
          node ./benchmarks/run.js
          PR_END_TIME=$(date +%s)
          PR_DURATION=$((PR_END_TIME - PR_START_TIME))
          echo 'Finished benchmarking, Start time: ${PR_START_TIME}, End time: ${PR_END_TIME}, Duration: ${PR_DURATION} seconds'
          echo "PR_TIME=${PR_DURATION}" >> $GITHUB_ENV

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout head benchmarks
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.base.ref }} -- benchmarks

      - name: Run benchmark on base branch
        id: base_benchmark
        run: |
          BASE_START_TIME=$(date +%s)
          node ./benchmarks/run.js
          BASE_END_TIME=$(date +%s)
          BASE_DURATION=$((BASE_END_TIME - BASE_START_TIME))
          echo 'Finished benchmarking, Start time: ${BASE_START_TIME}, End time: ${BASE_END_TIME}, Duration: ${BASE_DURATION} seconds'
          echo "BASE_TIME=${BASE_DURATION}" >> $GITHUB_ENV

      - name: Calculate percent change
        id: percent_change
        run: |
          echo "PERCENT_CHANGE=$(echo "scale=2; (${PR_DURATION} - ${BASE_DURATION}) / ${BASE_DURATION} * 100" | bc)" >> $GITHUB_ENV

      - name: Log benchmark results
        run: |
          echo "Time on pull branch: ${PR_DURATION} seconds"
          echo "Time on base branch: ${BASE_DURATION} seconds"
          echo "Time changed by ${PERCENT_CHANGE} percent"
